labels:
  platform: linux/amd64

variables:
  - &repo: cameleon.pkg-mirror.org/wwfyou/pgbackweb
  - &registry: cameleon.pkg-mirror.org

steps:
  build_dev:
    image: plugins/docker
    settings:
      username: sa_team_fishers
      password:
        from_secret: sa_team_fisher_pass
      repo: *repo
      registry: *registry
      labels:
        platform: linux/amd64
      tags:
        - dev
    when:
      event: [ push, manual, pull_request ]
      branch:
        - development

  build_master:
    image: plugins/docker
    settings:
      username: sa_team_fishers
      password:
        from_secret: sa_team_fisher_pass
      repo: *repo
      registry: *registry
      labels:
        platform: linux/amd64
      tags:
        - latest
    when:
      event: [push, manual, pull_request_closed]
      branch:
        - master

  build_with_tag:
    image: plugins/docker
    settings:
      username: sa_team_fishers
      password:
        from_secret: sa_team_fishers_pass
      repo: *repo
      registry: *registry
      platform: linux/amd64
      tags: ${CI_COMMIT_TAG}
    when:
      event: tag
